name: TimeTrace Library 

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: TimeTrace.sln
      Test_Project_Path: timetrace.library.tests/timetrace.library.tests.csproj
      NUGET_SOURCE_URL: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Execute unit tests
      run: dotnet test

    - name: Set version
      id: set_version
      run: echo "##[set-output name=VERSION;]1.0.${{ github.run_number }}"

    - name: Pack NuGet package
      run: dotnet pack timetrace.library/timetrace.library.csproj --configuration ${{ matrix.configuration }} /p:PackageVersion=${{ steps.set_version.outputs.VERSION }} --output ./artifacts

    - name: Upload NuGet package
      uses: actions/upload-artifact@v3
      with:
        name: nuget-package
        path: ./artifacts/*.nupkg

    - name: Publish NuGet package to GitHub Packages
      run: dotnet nuget push ./artifacts/*.nupkg --source ${{ env.NUGET_SOURCE_URL }} --api-key ${{ secrets.GITHUB_TOKEN }}
